### PR TITLE
Worked on expertise modal on vendor side

### PR DESCRIPTION
**Pull request by pundir95**
Worked on expertise modal on vendor side

### CODE REVIEW

**Review by rajinderrv — APPROVED** [review]

**Review by rajinderrv — DISMISSED** [review]

**Review by rajinderrv — APPROVED** [review]
fixed

**Review by rajinderrv — COMMENTED** [review]
done

**Review by rajinderrv — DISMISSED** [review]
approved

**Review by webexpert4rv — APPROVED** [review]
approved

**Review by webexpert4rv — APPROVED** [review]
approved

**Review by rajinderrv — DISMISSED** [review]
approve

**Review by rajinderrv — COMMENTED** [review]
approve

**Review by rajinderrv — COMMENTED** [review]
done

**Review by webexpert4rv — APPROVED** [review]
done

**Review by webexpert4rv — APPROVED** [review]
done

**Comment by rajinderrv** [comment]
done

**Review by rajinderrv — APPROVED** [review]
done

**Review by rajinderrv — DISMISSED** [review]
done

**Comment by webexpert4rv** [comment]
done

**Comment by webexpert4rv** [comment]
done

**Review by webexpert4rv — APPROVED** [review]
done

**Review by rajinderrv — COMMENTED** [review]
done

**Pull request merged**
